version: '26'

services:
  orders-db:
    container_name: orders_db
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data